<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2W5XEEh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2W5XEEh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2W5XEEh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2W5XEEh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2W5XEEh\App_KernelDevDebugContainer([
    'container.build_hash' => '2W5XEEh',
    'container.build_id' => '2817cbe5',
    'container.build_time' => 1627660905,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2W5XEEh');
