<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCznVAyZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCznVAyZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCznVAyZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCznVAyZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCznVAyZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'CznVAyZ',
    'container.build_id' => '3647f3db',
    'container.build_time' => 1628082285,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCznVAyZ');
