version: '3.7'
services:
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_PORT=3306
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lux
      - MYSQL_USER=lux_admin
      - MYSQL_PASSWORD=&pHDG3%LcV
    ports:
      - '4306:3306'
    volumes:
      - ./db:/var/lib/mysql
  php:
    container_name: php
    build:
      context: ./containers/php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/lux:rw
    depends_on:
      - database
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/lux:rw
      - ./containers/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
