version: '3.7'
services:
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_PORT=3306
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lux
      - MYSQL_USER=lux_admin
      - MYSQL_PASSWORD=&pHDG3%LcV
    ports:
      - '4306:3306'
    volumes:
      - ./db:/var/lib/mysql
    networks:
      default:
        ipv4_address: 172.18.0.2
  database_test:
    container_name: database_test
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_PORT=3306
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lux_test
      - MYSQL_USER=lux_admin
      - MYSQL_PASSWORD=&pHDG3%LcV
    ports:
      - '5306:3306'
    volumes:
      - ./db_test:/var/lib/mysql
    networks:
      default:
        ipv4_address: 172.18.0.7
  php:
    container_name: php
    build:
      context: ./containers/php
    ports:
      - '9000:9000'
    volumes:
      - ./containers/php/conf/php.ini:/usr/local/etc/php/php.ini
      - ./containers/php/conf/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./containers/php/conf/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./app:/var/www/lux:rw
    depends_on:
      - database
    networks:
      default:
        ipv4_address: 172.18.0.3
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/lux:rw
      - ./containers/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
    networks:
      default:
        ipv4_address: 172.18.0.4
  redis:
    container_name: redis
    image: redis:5-alpine
    ports: [6379]
    networks:
      default:
        ipv4_address: 172.18.0.5
  mailcatcher:
    container_name: mailcatcher
    image: schickling/mailcatcher
    ports: [1025, 1080]
    networks:
      default:
        ipv4_address: 172.18.0.6
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16